#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
touch /tmp/cacu
chmod 777 /etc/config/series
mac=`uci get network.wan_dev.macaddr`
sed -i '/option[[:space:]]mac[[:space:]]/d'  /etc/config/series
echo option mac "'${mac}'" >> /etc/config/series
echo "${mac}"|sed 's/://g' > /tmp/cacu
echo -n "${get_f}"|md5sum|cut -b 1-10 > /tmp/cacu
sed -i '/option[[:space:]]ID[[:space:]]/d'  /etc/config/series
get_s=`cat /tmp/cacu`
echo option ID "'${get_s}'" >> /etc/config/series
get_m=`cat /tmp/cacu`
echo -n "${get_m}"|md5sum|cut -b 10-20 > /tmp/cacu
get_q=`cat /tmp/cacu`
key=`cat /etc/config/series|grep key|cut -f 2|cut -b 13-23`
touch /tmp/key
echo "${key}" > /tmp/key
get_k=`cat /tmp/key`
if [ $get_q == $get_k ];
then cp /etc/mentohust.lua /usr/lib/lua/luci/controller/mentohust.lua
fi
}
